### ISSUE TITLE
Caching of extras

### ISSUE THREAD

**Issue by ArloL** [gwtbootstrap3/gwtbootstrap3-extras#105]
In accordance with https://github.com/gwtbootstrap3/gwtbootstrap3/issues/263 we should update these as well:

- [x] animate
- [x] bootbox
- [x] cachemanifest
- [x] card
- [x] datetimepicker
- [x] fullcalendar
- [x] growl
- [x] positionedtabs
- [x] respond
- [x] select
- [x] slider
- [x] summernote
- [x] toggleswitch

**Comment by ArloL** [comment]
I can't figure out which version of animate is used because it doesn't contain it in the css and I don't want to update either. Any ideas?

**Comment by ArloL** [comment]
Same for card and datetimepicker.

**Comment by jgodi** [comment]
I will look into them. The card is just custom css/js, so we can version that at 1.0 or just the same as the library

**Comment by ArloL** [comment]
Otherwise we can just give them names without versions. But we have to remember to include the version when updating.

**Comment by jgodi** [comment]
DateTimePicker is 2.2.0, forgot I added the versions on the demo.

http://gwtbootstrap3.github.io/gwtbootstrap3-demo/#dateTimePicker

**Comment by jgodi** [comment]
Animate.css is 3.2.0

**Comment by ArloL** [comment]
Last one missing is positionedtabs. Also custom code?

**Comment by jgodi** [comment]
Yes, custom code. Basically just a port over from Bootstrap 2.3.3 since they dropped support for these kinds of tabs.
