### ISSUE TITLE
Slider broken in IE 8

### ISSUE THREAD

**Issue by ArloL** [gwtbootstrap3/gwtbootstrap3-extras#114]
I get some weird behavior with Slider in IE 8. Somehow I get a `Object doesn't support this property or method` error when executing .slider(). Yet this http://jsfiddle.net/kxfk9qyt/4/embedded/result/ works.

Since there doesn't seem to be active development for Slider I would recommend to leave it as it is and add a message to the demo stating that IE 8 is broken.

**Comment by ArloL** [comment]
Maybe we should move to https://github.com/seiyria/bootstrap-slider

They don't support IE 8 either but it's under active development.

**Comment by jgodi** [comment]
I think we should move to that one too. Active Development would be best.

**Comment by ArloL** [comment]
OK. I agree with the 1.0 milestone.

**Comment by jgodi** [comment]
I will put the labels on the Demo for the 0.9 release though, so people will know.

**Comment by jgodi** [comment]
Added the note. Opened issue https://github.com/gwtbootstrap3/gwtbootstrap3-extras/issues/117 to switch over to the new, active slider.
