### ISSUE TITLE
Update Switch to latest version

### ISSUE THREAD

**Issue by jgodi** [gwtbootstrap3/gwtbootstrap3-extras#119]
Update switch to latest version and support any new features

**Comment by crevete** [comment]
I will make a PR for switch due to a critical bug : when creating a new toggle switch, it ALWAYS displayed with "ON" state even if the initial checkbox or radio button is not checked. I've spent many time to debug it, and the last version 3.3.2 gets it fixed.

**Comment by crevete** [comment]
Do you really want to close this ticket ? maybe leave this open util the next release ?

**Comment by ArloL** [comment]
You have a good point. So far we have always closed issues once they are on master.

I prefer a seperate develop branch myself. That is merged into master when released. This actually works really nice with GitHub. Since it then automatically closes the appropriate issues once they hit master.

What do you think @jgodi ?

**Comment by jgodi** [comment]
I prefer to close the issues once they are complete so that I can use the Milestone to track progress for the next release. I want to make faster releases, so that will be critical.

I think @crevete was suggesting that before the next release there will be more releases of the Switch Toggle, so we can always keep it updated.

As for the develop vs. master, I prefer master reflecting the next release for the Milestone tracking and just relative ease of one branch :)

**Comment by crevete** [comment]
@jgodi That's exactly what I mean.

**Comment by ArloL** [comment]
Is there some way to track our dependencies?

Maybe something like https://david-dm.org/ can help.

**Comment by jgodi** [comment]
I can look into it. Do you mind creating an issue to better track it? I will be busy until the weekend.

**Comment by ArloL** [comment]
Sure.
