### ISSUE TITLE
GrowlOptions no longer instaniatable 

### ISSUE THREAD

**Issue by mharray** [gwtbootstrap3/gwtbootstrap3-extras#125]
commit b806b67188732132dcd62a4daae6b5d63bf92958 removed the 'unused' GrowlHelper, however it was being used as a convenience function to instantiate GrowlOptions. So wondering if there was any further reasoning behind this, or if it's ok to re-commit that file - or move that code to GrowlOptions.java which probably makes more sense

**Comment by jgodi** [comment]
With all the changes/improvements to the Growl wrapper, it was no longer needed since a lot of the options have changed and become more robust. If you still need this Helper method, it seems more on a project by project basis because your base Options will be different than others.

**Comment by mharray** [comment]
Thanks for the reply. So how do we create a GrowlOptions instance? There's no constructor or factory methods, and it no longer extends JavaScriptObject, so I can't see a way to actually use it

**Comment by crevete** [comment]
@mharray
You can see examples here : http://gwtbootstrap3.github.io/gwtbootstrap3-demo/snapshot/#growl .
You can instantiate it like this : ```new GrowlOption()```. I was also wondering why GrowlOption does not extend JavaScripObject, but it works fine...

**Comment by mharray** [comment]
thanks crevete, I swear that wasn't working for me when I first raised the issue, but all working now :)
