### ISSUE TITLE
DateTimePicker setFormat - mapping is invalid

### ISSUE THREAD

**Issue by strackam** [gwtbootstrap3/gwtbootstrap3-extras#138]
There is something wrong when using a format with month in text (long date format).
It should work with "dd MM yyyy" as explained in the doc (http://www.malot.fr/bootstrap-datetimepicker/#options).
But the "MM" part is not mapped correctly to initiate the dateTimeFormat (should be translate to "dd MMMM yyyy").

It doesn't fails when using setValue because hopefully the DateTimeFormat.parse understand 31 01 2014 as the last day of January. But the format function traduces MM as number so the textBox is incorrect.

The same error occurs when using "dd M yyyy" for a medium format (M stands for text abreviation of the month) which should be translate to "dd MMM yyyy".

**Comment by ahumellihuk** [comment]
I would recommend merging pull request https://github.com/gwtbootstrap3/gwtbootstrap3-extras/pull/182, which would solve this problem.
