### ISSUE TITLE
Select.deselectAll() does not work - since 0.9 release

### ISSUE THREAD

**Issue by joolsT1311** [gwtbootstrap3/gwtbootstrap3-extras#141]
I've just upgraded an application from 0.8.1 to 0.9.

The deselectAll() method on the Select component no longer deselects items.

**Comment by crevete** [comment]
@joolsT1311 maybe you are talking about this https://github.com/silviomoreto/bootstrap-select/issues/721 ? This is fixed in the version 1.6.4

**Comment by eliovir** [comment]
@joolsT1311 I've got the same problem. To workaround, I used `.setValue("")`.

**Comment by joolsT1311** [comment]
@eliovir Thanks for your suggestion - yes I've worked around the issue (not elegantly though as the setValue methods do not immediately change the selected values in the model - complex forms with inter-dependent fields suffer...). Will be good to get the fix in though - I think it may well be caused by the issue linked to by @crevete (thanks).
