### ISSUE TITLE
Suggestion: nicer confirm popup

### ISSUE THREAD

**Issue by nkg753** [gwtbootstrap3/gwtbootstrap3-extras#160]
Confirm popup is very useful feature and i used in almost all web applications.

Bootbox confirm (example: http://gwtbootstrap3.github.io/gwtbootstrap3-demo/#bootbox) works very well, but I found http://ethaizone.github.io/Bootstrap-Confirmation/ - it is nicer.

Can you implement it?

**Comment by jgodi** [comment]
Having too many wrapped libraries under the 'Extra's' here will get dangerous. We already have the Bootbox. If you need something like this for your project I would suggest wrapping it yourself in your project and using it.

Thanks for the suggestion though!
