### ISSUE TITLE
DateTimePicker Tabbing error

### ISSUE THREAD

**Issue by manny73** [gwtbootstrap3/gwtbootstrap3-extras#163]
Hi,
with only Chrome, both in windows and in Mac, when tab over field the focus not go on the next field but re-begin from the first and loop.
You can test this 'possible bug' directly on the demo site: http://gwtbootstrap3.github.io/gwtbootstrap3-demo/#dateTimePicker

Thanks

Manny

**Comment by remarkNS** [comment]
It happens because in onHide(final Event e) of DateTimePickerBase class, focus has been removed from textBox. If you want it to stay there (to tab to next field) override this method in your class and instead of textBox.setFocus(false) put getTextBox().setFocus(true); BTW the same thing happens with DatePicker, you can solve this the same way.

**Comment by jgodi** [comment]
Now the question is, is this a suitable solution or should we try to address this?

**Comment by mtraum** [comment]
The problem with this workaround is it makes autoClose impossible, because you set the focus and then it pops up the picker again.

To work around that, I did this:
```java
    // Set focus back to textbox so tabbing will still work
    addHideHandler(new HideHandler() {
      @Override
      public void onHide(HideEvent hideEvent) {
        getTextBox().setFocus(true);
        hideWithoutFiringEvent(getElement());
      }
    });
...
  public static native void hideWithoutFiringEvent(Element e)/*-{
                                                             $wnd.jQuery(e).next().hide();
                                                             }-*/;
```

**Comment by crevete** [comment]
When modal is displayed, the natural behavior (like the native JS lib) is:
- when clicking outside the text box, the focus is lost
- when clicking inside the text box, the focus is kept
- when hitting ``ESC`` (to hide the modal), the focus is kept in the text box
