### ISSUE TITLE
Add validation support for DatePicker, DateTimePicker and Select

### ISSUE THREAD

**Issue by sjardine** [gwtbootstrap3/gwtbootstrap3-extras#164]
DatePicker, DateTimePicker and Select are missing validation support.

**Comment by crevete** [comment]
I cannot see why Select needs to be validated.

**Comment by sjardine** [comment]
The only validator I think could be beneficial would be the BlankValidator.  An error would occur when a select is required, there is a blank default option, and the user doesn't complete the field.

**Comment by entzik** [comment]
As per Steven's request I am adding some use cases for DatePicker validation I have posted on the Google group:
1) forms with "start date" / "end date" fields: these are quite common and generally we need to validate that the end date is past the start date, sometimes the start date must not be in the past or must satisfy other requirement such as being a legally working day
2) schedule editors: in general when adding dates to a schedule it is  required to validate that the chosen date is within a specific range, that it is not a weekend day, a public holiday in one or more countries, or satisfy other domain specific requirements.

I agree Select may not need validation. The only scenario I can think this could be useful is when, depending on context, some available options would be illegal, but personally in such cases I prefer to reset the  option list when the context changes.

**Comment by crevete** [comment]
@entzik on Select validation, I agree with you. Developers should do the necessary to "avoid" validation errors on select.

Personally I'm not fan to put validation support for widgets in gwtbootstrap-extra project. Theses widgets are not native HTML widgets, but just a wrapper of third-party JS library. The DOM structure may be changed when they are physically attached. Basically, some native GWT Widget methods may not correctly work (i.e. : setValue(), getValue(), setVisible(), etc.) : ideally you always need to check ```isAttached()``` inside the method. Unfortunately most of existing widgets do not do this. So if you continue to add the validation support on these wrappers, it's just like adding a second layer on it, and it will ONLY work when they are attached. That's much more complicated to correctly handle it. If one day the native JS library has an evolution on DOM structure, the validation support may be immediately broken. That needs much more time to get it work again. IMP, these wrapper widgets should be as simple as possible.

**Comment by entzik** [comment]
fair enough, I'll work around this. thanks for looking into it.

**Comment by sjardine** [comment]
I have spent a bit of time looking at the code for these and DatePicker and DateTimePicker use a TextBox as the input field which already has validation support.  I really don't see how we are adding any layers by exposing the validation functions of the underlying TextBox.

As far as Select goes, I concur with @crevete and @entzik.  We should just leave it as is.

**Comment by crevete** [comment]
It seems that DataPicker and DateTimePicker auto-validate it's value (on the demo page). Wrong values are automatically converted to valid ones. In this case, why you want to add validation support ?

**Comment by sjardine** [comment]
I can see a number of use cases where a validated date is important.  In my business, transportation,  we have several required dates, some cannot be in the future, some cannot be in the past, some must be a specific day of the week (ex: Friday).  Also, the JSR-303 bean validation provide annotations for Future and Past on Date and Calendar types.  Without validation support, we would not be able to provide meaninful JSR-303 bean validation for forms with this requirement using DatePicker and DateTimePicker.

**Comment by remarkNS** [comment]
I agree with @sjardine that date validations are important.

**Comment by jgodi** [comment]
+1

**Comment by crevete** [comment]
@sjardine you are talking about functional validation but I just think about syntax validation. Well, why not, if the original textbox is not modified by the native JavaScript library. But beware anyway!

**Comment by BenDol** [comment]
My having validation on the Select widget is important in the use case with Multiselect enabled, where you have the option not to select anything. That was what I needed it for anyway.
