### ISSUE TITLE
FullCalendar no longer works

### ISSUE THREAD

**Issue by koljascasino** [gwtbootstrap3/gwtbootstrap3-extras#166]
In the v1.0-SNAPSHOT demo, clicking on the Run Example button throws a java script error.
`Uncaught ReferenceError: moment is not defined`

Could be related to a missing entry point class entry in _FullCalendar.gwt.xml_ which was removed in 
478a5bbc5a9c9bd27fe43a1f936c9ce178056a16, not sure why this was removed.

**Comment by jgodi** [comment]
Good catch, I will fix this today.

**Comment by jgodi** [comment]
https://github.com/gwtbootstrap3/gwtbootstrap3-extras/pull/167 fixes it
