### ISSUE TITLE
Notify notifications are shown behind modals.

### ISSUE THREAD

**Issue by flirtomania** [gwtbootstrap3/gwtbootstrap3-extras#172]
White opened modal and green notification behind it.

![modal over notification](https://cloud.githubusercontent.com/assets/6590011/7249774/8398e424-e825-11e4-9890-16d48f0d1015.png)

**Comment by crevete** [comment]
@jgodi @flirtomania No this is not a bug. The default z-index value of the Notify library is 1031, smaller than bootstrap modal z-index.
You just need to change the zIndex settings to override the default one :
```
NotifySettings settings = NotifySettings.newSettings();
settings.setZIndex(xxx); // A big z-index value
```

**Comment by jgodi** [comment]
Thanks for investigating and commenting.
