### ISSUE TITLE
Notify entry point bug in classic DevMode 

### ISSUE THREAD

**Issue by ahumellihuk** [gwtbootstrap3/gwtbootstrap3-extras#176]
When GWT module inherits Notify and the app is run in classic DevMode the app throws an Exception saying that "Something other than a boolean was returned from JSNI method". The method that throws it is `NotifyEntryPoint.isNotifyLoaded()`.
It needs to be changed to be exactly like the one in `GrowlEntryPoint`:
`if ($wnd.jQuery && $wnd.jQuery.notify) {`
`return true;`
`} else {`
`return false;`
`}`

**Comment by jgodi** [comment]
Able to submit a PR for this?

**Comment by ahumellihuk** [comment]
Will do later

**Comment by crevete** [comment]
@jgodi @ahumellihuk I've never tested with classic dev mode. So this may be closed ?

**Comment by worknperk** [comment]
This defect is still an issue.

**Comment by jgodi** [comment]
Super dev mode is the best practice so not sure if the time or effort should be placed into this.

**Comment by rmjohn08** [comment]
So this plugin cannot be use in classic dev mode? Really liked it but i like classic dev mode for development.

**Comment by davidbuhler** [comment]
You can usr the gwtbootstrap3 library with classic dev mode, but to do so, you need to run FireFox 24 ESR and Eclipse Luna.

I'm not sure about Intellij support for Classic Dev Mode, but he FireFox part would still hold true.

**Comment by rmjohn08** [comment]
Hello David,
I am trying the Notify extra within the gwtbootrap3-extra. I have
downloaded FF 24.2 esr and working on Luna with gwt 2.6.1

I am getting an exception onModuleLoad () NotifyEntryPoint

Something other than a boolean was returned from JSNI method @
org.gwtbootstrap3.extras.notify.client.NotifyEntryPoint.

If i do SuperDevMode it loads.

**Comment by davidbuhler** [comment]
I had the same issue. I ended up using the  native Notify library with JSNI. Worked fine.

**Comment by rmjohn08** [comment]
Sorry I am not well experienced on the gwt plugin world. Would you be able
to provide bit more details on how you did that? I am not following when
you mentioned using the Notify library with JSNI.

Were you be able to continue using classic dev mode?
