### ISSUE TITLE
Growl has been removed ?

### ISSUE THREAD

**Issue by biancashouse** [gwtbootstrap3/gwtbootstrap3-extras#179]

**Comment by biancashouse** [comment]
Looks like the extra has been renamed Notify. 

Growl.growl(...) -> Notify.notify(...)
GrowlOptions -> NotifySettings
GrowlOptions.setPosition(GrowlPosition... -> NotifySettings.setPlacement(NotifyPlacement...

So phew !

**Comment by jgodi** [comment]
Yes, Growl was removed in favor of the Notify. Didn't make sense to have both.

**Comment by biancashouse** [comment]
Quite right.

BTW - I'm starting to use flexbox more and more, and was wondering if
bootstrap and/or your gwt-bootstrap will be integrating it any time soon ?

**Comment by jgodi** [comment]
Since we are a wrapper for Bootstrap, whatever they use then we will use. I am not sure in Bootstrap4 if they are planning to use flex box or not, but they are overhauling the grid system, so maybe.
