### ISSUE TITLE
DateTimePicker highlights wrong month as "active"

### ISSUE THREAD

**Issue by martinmatthias** [gwtbootstrap3/gwtbootstrap3-extras#180]
DateTimePicker highlights the wrong month as "active" (blue background). This can be seen in the demo as well - if you click on "May 2015", you`ll see "March" highlighted, which is obviously not correct. 
It seems, that the highlighted month is always 2 months "behind" the month actually set. If I set a date in July, May is highlighted as "active" month afterwards.
This is no functional issue, but somehow annoying for users.

![datetimepicker-wrong month highlighted](https://cloud.githubusercontent.com/assets/8134451/7511862/86783afc-f4a8-11e4-9651-1426906828eb.png)

**Comment by jgodi** [comment]
Can you see if this bug is in the base JS library?

**Comment by martinmatthias** [comment]
Hi there,

actually I found out this: smalot/bootstrap-datetimepicker/issues/277
Looks like the proposed Fix has never been contributed to the project, what a shame. 
The project looks quite dead. I`m in doubt that this will be fixed ever. ;(

**Comment by crevete** [comment]
This is fixed when upgrading to dateTimePicker 2.3.5
