### ISSUE TITLE
Slider: SliderOption.getDataAttribute() returns incorrect attribute name

### ISSUE THREAD

**Issue by erik360** [gwtbootstrap3/gwtbootstrap3-extras#185]
`SliderOption.getDataAttribute()` should replace underscores ( _ ) in the attribute name with dashes ( - ). This function is used in many places and where the data attribute name is underscored, like `tick_labels`, the correct data attribute is `data-slider-tick-labels`. This breaks functions such as `setTicksLabels` when called before the slider is attached to the DOM (ie during initialization).

**Comment by crevete** [comment]
@erik360 You are right; But their documentation is not very clear...
