### ISSUE TITLE
Select.setLanguage() escapes title attribute

### ISSUE THREAD

**Issue by eliovir** [gwtbootstrap3/gwtbootstrap3-extras#192]
Locale strings of Select contain HTML escaped characters, for example the French translation [in GWTBootstrap3](https://github.com/gwtbootstrap3/gwtbootstrap3-extras/blob/master/src/main/resources/org/gwtbootstrap3/extras/select/client/resource/js/locales.cache.1.6.4/defaults-fr_FR.min.js) as well as [in original library](https://github.com/silviomoreto/bootstrap-select/blob/master/js/i18n/defaults-fr_FR.js).

Using `select.setLanguage(SelectLanguage.FR);` generates a button with `title` attribute containing the twice escaped string `Aucune s&amp;eacute;lection` instead of `Aucune s&eacute;lection`.

This is the generated HTML code for the button:
```
<button data-toggle="dropdown"
 class="btn dropdown-toggle form-control selectpicker btn-default"
 type="button"
 title="Aucune s&amp;eacute;lection"
 aria-expanded="false">
<span
 class="filter-option pull-left">Aucune sélection</span>&nbsp;<span
 class="caret"></span>
</button>
```

NB: this issue does not occur in the original library (tested adding `<script src="js/i18n/defaults-fr_FR.js"></script>` to [test.html](https://github.com/silviomoreto/bootstrap-select/blob/master/test.html)).

**Comment by crevete** [comment]
@eliovir I've just tested with the last version of select, the issue DOES OCCUR in the original library. The problem is in the ```defaults-fr_FR.min.js```. They should not use accented characters (```Aucune sélection```) rather than HTML entities (```Aucune s&amp;eacute;lection```). The best solution is to create an issue in the original library. But for our library, we could fix the translation for FR.
