### ISSUE TITLE
Cards don't work in Firefox

### ISSUE THREAD

**Issue by payammeyer** [gwtbootstrap3/gwtbootstrap3-extras#195]
When the trigger icon is pushed, the front gets inverted (mirrored?) and is still visible while the back is also visible:
![image](https://cloud.githubusercontent.com/assets/9900587/8781604/0d38022e-2ede-11e5-8d05-54573d2d15c5.png)

I went as far back as Firefox 31 and they all behave the same way.

**Comment by sjardine** [comment]
Would you please provide some sample code?  I would suggest forking https://github.com/gwtbootstrap3/gwtbootstrap3-sample-app and then creating a view that showcases the problem.

Thanks!

**Comment by payammeyer** [comment]
I'm not sure if I understand what you mean. If you just use the current demo for Cards (https://gwtbootstrap3.github.io/gwtbootstrap3-demo/#card) in Firefox, you'll see the issue I'm referring to here. I confirmed that it's not something on the recent version of Firefox and went as far back as Firefox 31. Does that make sense?

**Comment by sjardine** [comment]
Yes.  This is a verified bug from Mozilla.  I will apply the fix.
