### ISSUE TITLE
DatePicker: popup closing when value change from textbox

### ISSUE THREAD

**Issue by mickaelbaron** [gwtbootstrap3/gwtbootstrap3-extras#203]
Hi,

I found a strange behaviour when the user changes the value of the date from the textbox. For each modification from the textbox, the popup is closing. I think is a bad idea. 

I fix this ui problem by overiding the DatePickerBase#onChangeDate method. Here is the new code
```
    @Override
    public void onChangeDate(final Event e) {
        fireEvent(new ChangeDateEvent(e));
        ValueChangeEvent.fire(DatePickerBase.this, getValue());
        // hide();
    } 
```

What do you think about this workaround ?

Mickael

**Comment by sjardine** [comment]
The whole point of the dialog is for the use to select a date.  I think hiding the dialog when a date is more intuitive.  I don't think we should change this.

@crevete What do you think?

**Comment by crevete** [comment]
@sjardine I think hiding the dialog is necessary because when user changes the value in the textbox, nothing guarantee the input is valid, in this case the popup cannot display the correct date. So for now, I think the behaviour is normal.

**Comment by mickaelbaron** [comment]
Thanks for your responses. But i keep my workaround ;-)

Mickael

**Comment by crevete** [comment]
@mickaelbaron as you wish :-)

**Comment by crevete** [comment]
@mickaelbaron I reopen this issue, because this causes #242. You are right, the ``hide()`` method should not be called here. In fact, the syntax validation is ensured by the native javascript lib when losing the focus on text box.
