### ISSUE TITLE
DatePicker: HasFormat be consistent with GWT's DateTimeFormat

### ISSUE THREAD

**Issue by manstis** [gwtbootstrap3/gwtbootstrap3-extras#206]
Hi,

I found ```DatePicker.HasFormat``` patterns are inconsistent with GWT's ```DateTimeFormat``` patterns; most particularly (for my use-case at least) ```M```. GWT-BS3 processes ```M``` as "short textual representation of a month, three letters" (e.g. "Jan") whereas GWT would give the numeric month number (e.g. "1"). This is troublesome where I wish to show a ```Date``` in a ```DatePicker``` in some scenarios and (for example) as a ```Label``` in others.

Is there a utility "mapping" class, to convert GWT's pattern to/from GWT-BS3's pattern; or are there plans to consolidate the patterns (now someone's going to say GWT-BS3's patterns are consistent with BS3 and it's GWT that's the odd one out!!)

Thanks.

Mike

**Comment by sjardine** [comment]
There is not a mapping utility.  Would you be willing to provide a PR for this?

**Comment by manstis** [comment]
I will be writing something to suit our needs and will happily submit it as
a PR. Do I need to sign a Contributor Agreement or anything (our, Red Hat,
legal department would need to agree). Do you also have a particular place
for tests?

**Comment by sjardine** [comment]
No contributor agreement necessary.  All code in this repository is governed by the Apache 2.0 license.  Thanks!

**Comment by crevete** [comment]
The PR #182 (the ``setGWTFormat()`` method) should fix this issue, as mentioned @sjardine in the PR #207. And it is available in the 0.9.1 release.
