### ISSUE TITLE
unable to use select

### ISSUE THREAD

**Issue by bbbalabhaskar** [gwtbootstrap3/gwtbootstrap3-extras#223]
I am getting following error when i'm using select

Uncaught com.google.gwt.user.client.ui.AttachDetachException: Exception caught: Exception caught: Exception caught: Exception caught: Exception caught: (TypeError) : $wnd.jQuery(...).selectpicker is not a function

**Comment by crevete** [comment]
Can you please provide a sample code?

**Comment by bbbalabhaskar** [comment]
I have done nothing new 
I added dependency in my pom, and my gwt.xml file,

but when I add select like below i got that error, can you help me
<select:Select>
  <select:Option text="..."/>
  <select:Option text="..."/>
  <select:Option text="..."/>
</select:Select>

i am using gwt 2.7

**Comment by crevete** [comment]
maybe jQuery is load loaded ? Or you can check out our demo project. There are some working examples.

**Comment by bbbalabhaskar** [comment]
I'm very sure that jQuery is injected in in window as i am doing it manually in other place for some native js implementation regarding canvas.

BTW thanks, for responding and all the other features are working without any problem.

**Comment by sjardine** [comment]
This error looks like jQuery is getting loaded multiple times. Which module are you adding to your gwt.xml?

**Comment by sjardine** [comment]
Also, its impossible for us to troubleshoot a problem we cannot see. Please fork the gwtbootstrap3-sample project and modify it so it exhibits your problem. Then we can troubleshoot much easier.

**Comment by bbbalabhaskar** [comment]
Thanks for suggestion i could be able to resolve the problem, and as you said it was due to reason that jQuery is injecting multiple times and i think issue can be closed.

**Comment by bhagyalakshmisabbella** [comment]
How we can know jQuery is injecting multiple times and if so how can we avoid it.

**Comment by sjardine** [comment]
I would suggest not using modules that use the script injector.  Inherit from the "no resources" or "no theme" modules and then inject the difference scripts you need in your index.html.

This gives you the most control over how and when the scripts are injected.
