### ISSUE TITLE
Animate.animate is not wrking as expected

### ISSUE THREAD

**Issue by VitaliyKulikov** [gwtbootstrap3/gwtbootstrap3-extras#226]
possiably not issue, but need rework.

**usage**: ```Animate.animate(button, Animation.FLASH, -1, 2000, 5000);```
**expected**: infitive animatation with delay 5000ms before every 2000ms of animation
**actual**: delay 5000ms only once before infitive animatation

**Comment by crevete** [comment]
The Javadoc says:
```
@param delay Delay before starting the animation loop in ms. Value <= 0 means no delay.
```
Here the ```delay``` is only the first one before animation loop, but not before every animation.
