### ISSUE TITLE
Multiple inherits causing problem

### ISSUE THREAD

**Issue by bbbalabhaskar** [gwtbootstrap3/gwtbootstrap3-extras#227]
Previously I had an issue with select in extras which caused due to multiple injection of jQuery in browser window. I am facing same issue when i inherit multiple modules in my gwt.xml file. I would like to know if there is any other way to include multiple modules without any problem.

**Comment by sjardine** [comment]
Personally, I prefer to manually inject resources instead of automatic injection. Just inherit the "NoResources" modules and then add script/css tags to your html file(s).

**Comment by crevete** [comment]
In your module EntryPoint file, you should do something like this to ensure the jQuery is not injected several times: 
```
@Override
public void onModuleLoad() {
    if (!isJQueryLoaded()) {
        // Inject jQuery
    }
    ...
 }
private native boolean isJQueryLoaded() /*-{
     if ($wnd.jQuery) {
        return true;
     }
     return false;
}-*/;
```

**Comment by bbbalabhaskar** [comment]
It was nice to hear two suggestions, I would like to tell you that in my project I am doing the way you said(injected jQuery like you said), and is working fine. But my problem is when I am including more than one module of your extras in my project. for me possible way is to inherit noResource, Thanks.

**Comment by bbbalabhaskar** [comment]
I am unable to check code of Notify widget in your source available. I would like to know if it is removed I'm getting problem when I'm using it.

**Comment by sjardine** [comment]
Both the gwtbootstrap3 and gwtbootstrap3-extras jar files should contain the source otherwise gwt wouldn't compile.

**Comment by sjardine** [comment]
Both solutions to the multiple inheritance problem should work.  Closing...
