### ISSUE TITLE
DatePicker and DateTimePicker keyboard support is broken

### ISSUE THREAD

**Issue by FrankW76** [gwtbootstrap3/gwtbootstrap3-extras#242]
When using the keyboard to enter a Date weird things happen.

In the demo of the normal bootstrap version of DatePicker : http://eternicode.github.io/bootstrap-datepicker/?markup=input&format=&weekStart=&startDate=&endDate=&startView=0&minViewMode=0&maxViewMode=2&todayBtn=false&clearBtn=false&language=en&orientation=auto&multidate=&multidateSeparator=&keyboardNavigation=on&forceParse=on#sandbox

You can for example enter a date like : 05/24/2014 and it will work no problem.
You can also delete the date using backspace no problem.

When you try to do this in the gwt-bootstrap version (this can be tested on the demo page (http://gwtbootstrap3.github.io/gwtbootstrap3-demo/snapshot/#datePicker) try to enter 05/24/2014 in the textbox. You will see that this is impossible. Your entered value is auto commited after some keypresses.

Also after you pick a date with the mouse. Try using backspace in the textbox. This will not work.

These issues arrise in both the DatePicker as in the DateTimePicker.

**Comment by FrankW76** [comment]
DateTimePicker actually appears to be working quite decently.
It is especially the DatePicker for which the keyboard support is completely broken.

**Comment by crevete** [comment]
See #203 for more details. The ``hide()`` method makes the keyboard broken.
