### ISSUE TITLE
DateTimePicker navigation is broken

### ISSUE THREAD

**Issue by FrankW76** [gwtbootstrap3/gwtbootstrap3-extras#244]
Open any DateTimePicker on https://gwtbootstrap3.github.io/gwtbootstrap3-demo/#dateTimePicker

Click on the arrows to navigate to next/previous period. All kinds of weirds unsuspected things will happen.

When doing this on the demo of the wrapped js library all is normal : http://www.malot.fr/bootstrap-datetimepicker/demo.php?utm_source=siteweb&utm_medium=demo&utm_campaign=Site%2BWeb

**Comment by FrankW76** [comment]
Fixed by upgrading js library to 2.3.5.
See pull request : https://github.com/gwtbootstrap3/gwtbootstrap3-extras/pull/246

**Comment by crevete** [comment]
@FrankW76 can you please repair the demo page ?
