### ISSUE TITLE
Slider is disable after update from 0.9.1 to 0.9.2

### ISSUE THREAD

**Issue by Grishas** [gwtbootstrap3/gwtbootstrap3-extras#256]
Slider is in disable state after update from 0.9.1 to 0.9.2

![image](https://cloud.githubusercontent.com/assets/6190126/12030881/e77d17b8-ae0d-11e5-84f0-eae0b13f22c8.png)

Please advice

**Comment by crevete** [comment]
Please provide your sample code. In our demo page, all works fine : 

http://gwtbootstrap3.github.io/gwtbootstrap3-demo/#slider

**Comment by Grishas** [comment]
Sorry it seems issue in my code

Please provide your sample code. In our demo page, all works fine :

http://gwtbootstrap3.github.io/gwtbootstrap3-demo/#slider

—
Reply to this email directly or view it on GitHub
<https://github.com/gwtbootstrap3/gwtbootstrap3-extras/issues/256#issuecomment-167754420>
.
