### ISSUE TITLE
Image gallery controls not showing

### ISSUE THREAD

**Issue by clintonbosch** [gwtbootstrap3/gwtbootstrap3-extras#264]
It seems as though there might be an issue with showing the controls (prev button, next button, close button and indicator). I have tried setting them as follows 

        gallery.setShowCloseButton(true);
        gallery.setShowIndicator(true);
        gallery.setShowNextButton(true);
        gallery.setShowPrevButton(true);

But I can not see any controls when viewing the lightbox

**Comment by crevete** [comment]
Please se my reply in #453
