### ISSUE TITLE
How to add open/close handler for drop-down menu of the multiselect?

### ISSUE THREAD

**Issue by shabak** [gwtbootstrap3/gwtbootstrap3-extras#266]
In my case I need to do some actions just after closing drop-down menu, not on checking, since I use multiselect mode of the control. Thanks!

**Comment by crevete** [comment]
In the current version, no event handler is wrapped. This widget needs work anyway :
http://silviomoreto.github.io/bootstrap-select/options/#events

**Comment by shabak** [comment]
Here is a solution: http://stackoverflow.com/questions/34931853/gwtbootstrap3-extras-select-how-to-add-open-close-handler-for-drop-down-menu-of

**Comment by crevete** [comment]
One more time, this should be reworked and included in the library. You can do anything by extending the select widget for now, but it is not a good solution.

**Comment by shabak** [comment]
for sure

**Comment by crevete** [comment]
FYI, now you can call ```addHideHandler``` or ```addHiddenHandler``` to do what you want.

For more details, please see http://gwtbootstrap3.github.io/gwtbootstrap3-demo/snapshot/#select
