### ISSUE TITLE
DatePicker doesn't work with setFormat("dd/mmmm/yyyy");

### ISSUE THREAD

**Issue by davepuppets** [gwtbootstrap3/gwtbootstrap3-extras#271]
My code look like something like this:
`DatePicker datePicker = new DatePicker();`
`datePicker.setFormat("dd/mmmm/yyyy");`

And then, when I try to pick up a date with the visual element, 
I get this:

> 02/022/2016

instead of

> 02/February/2016

We get a similar problem with `datePicker.setFormat("dd/mmm/yyyy");`

**Comment by ahumellihuk** [comment]
To use GWT date/time format, you need to use setGWTFormat(String pattern) method instead of setFormat(String pattern), which only accepts Bootstrap format.

**Comment by davepuppets** [comment]
It works, thanks a lot!
