### ISSUE TITLE
Add Method GetAllSelectedOptions to Select.MultipleSelect

### ISSUE THREAD

**Issue by peterdresslar** [gwtbootstrap3/gwtbootstrap3-extras#279]
Rather than returning List<String> as in GetAllSelectedValues() this method would return List<Option>. This would enable much easier programmatic access to adding a Selected Option to the Select.

**Comment by crevete** [comment]
I'm not sure I understand what we want exactly. In your fix, you just add a **private** method. Why private? If you just want to add a method to get all select options, I could add this in an another PR. Please let me know what you want exactly.
