### ISSUE TITLE
DatePicker incorrect behavior when navigating using tab key

### ISSUE THREAD

**Issue by lucasbmenezes** [gwtbootstrap3/gwtbootstrap3-extras#292]
When filling up a form using tab key to skip or to go to the next input, and a DatePicker input is reached, instead of continue to the next input field it returns to the first focusable element on the page.

**Comment by crevete** [comment]
In our demo page, when I hit the Tab key, the focus moves to the next focusable element, and it does not return to the first focusable element.

**Comment by lucasbmenezes** [comment]
I couldn't make it work on http://gwtbootstrap3.github.io/gwtbootstrap3-demo/#datePicker. 
Here are the SS. 

DatePicker opened > Tab key pressed
<img width="545" alt="screen shot 2016-03-29 at 08 07 06" src="https://cloud.githubusercontent.com/assets/4417397/14106017/43d25730-f585-11e5-9835-d9302ab6d107.png">

This get focused and it shouldn't. The right one is the "Position" input below the "Setting Languages" input.
<img width="539" alt="screen shot 2016-03-29 at 08 07 09" src="https://cloud.githubusercontent.com/assets/4417397/14106016/43cf693a-f585-11e5-92b8-586638a520a0.png">

**Comment by crevete** [comment]
I've tested with Firefox 45, it seems it works. But you are right, on Chrome 49, it does not work
