### ISSUE TITLE
select issue after upgrade from 0.9.2 to 0.9.3

### ISSUE THREAD

**Issue by Grishas** [gwtbootstrap3/gwtbootstrap3-extras#294]
thirst of all thanks for great widgets!

after upgrade from 0.9.2 to 0.9.3
 
got follow error:

 Invoking generator com.google.gwt.uibinder.rebind.UiBinderGenerator
                  [ERROR] Field 'selectSection' does not have an 'addChangeHandler' method associated.
         [ERROR] Errors in 'com/ctnf/client/activities/compare/CompareViewImpl.java'
            [ERROR] Line 87: Failed to resolve 'com.ctnf.client.activities.compare.CompareViewImpl.CompareViewImplUiBinder' via deferred binding
         [WARN] For the following type(s), generated source was never committed (did you forget to call commit()?)
            [WARN] com.ctnf.client.activities.compare.CompareViewImpl_CompareViewImplUiBinderImpl
      [ERROR] Compiler returned false

ui:	<select:MultipleSelect header="You can type section for search and then select" width="100%" ui:field="selectSection" title="Filter" liveSearch="true" style="PRIMARY"/>

code:
@UiField MultipleSelect selectSection;

init()

this.selectSection.clear();
Collections.sort(ticketBlocks,new AlphanumComparator(SortBy.section));
for(...)
Option option = new Option();
option.setText( section );
selectSection.add(option);	
}
		}	
		
		this.selectSection.refresh();		

Please advice

**Comment by Grishas** [comment]
sorry for noise its my mistake

**Comment by crevete** [comment]
@Grishas Could you close this issue?

**Comment by Grishas** [comment]
yes
