### ISSUE TITLE
Date (Time) Picker fires ValueChangeEvent when setting value into it with 'fireEvents' == false

### ISSUE THREAD

**Issue by ahumellihuk** [gwtbootstrap3/gwtbootstrap3-extras#312]
When you call setValue(value, false), you expect the date picker to just update its value, but not fire ValueChangeEvent. Unfortunately, this is exactly what happens. In JS library there is a check whether the new value was passed in to the update() function, and if it wasn't then it fires a 'changeDate' event. Is there a specific reason for using update() function, but setting the new value directly into the textbox before calling it?

**Comment by crevete** [comment]
Setting the new value directly into the textbox before calling the ```update```function may be due to the date format issue.
