### ISSUE TITLE
DateTimeBox doesn't work correctly when tabbing through fields in Chrome 34

### ISSUE THREAD

**Issue by snowe2010** [gwtbootstrap3/gwtbootstrap3-extras#32]
It seems that either the DateTimeBox doesn't implement the correct tabIndex or that it somehow resets the tabindex to 0 when trying to tab through it. You can see the issue on the demo page. https://gwtbootstrap3.github.io/gwtbootstrap3-demo/#dateTimePicker

Attempting to tab from the first datebox to the second results in tabbing up to the header. If you continue to tab through the header you will make it back to the date box and the process will start over again.

**Comment by jgodi** [comment]
Any update on this? Still cannot replicate this issue.

**Comment by snowe2010** [comment]
No, I was moved to a different team not using the extras about a month after the last post. I wasn't able to ever figure it out. You can probably close it. I'll open it if I ever come across this problem again.
