### ISSUE TITLE
Datepicker - unable to mask text

### ISSUE THREAD

**Issue by reachaish** [gwtbootstrap3/gwtbootstrap3-extras#330]
I'm trying to set the datepicker textBox text to a masked value with forceParsed set to false and the framework automatically changes that to a current date.

**Comment by crevete** [comment]
Are you sure that is a bug of gwtbootstrap3-extras wrapper ? As you can see in the source code, the wrapper does simply pass the ```forceParse``` value to the datePicker. Please make a jsfiddle to see if it is a bug of datePicker. If so, you may create an issue in that project. Thanks

**Comment by crevete** [comment]
@reachaish Without your reply, I will close this issue.

**Comment by reachaish** [comment]
Hello @crevete , Sorry i'm late with the response. I was able to get the masking done onBlur with forceparse set to false,, i'm unable to edit the month/year in the datepicker maybe because i'm overriding the DOM handlers.

               dob.setForceParse(false);
		dob.addDomHandler(new BlurHandler() {			
			@Override
			public void onBlur(BlurEvent event) {				
				dob.getTextBox().setText(**masked value**);
			}
		}, BlurEvent.getType());
		dob.addDomHandler(new FocusHandler() {			
			@Override
			public void onFocus(FocusEvent event) {
				dob.setValue(**unmasked value**);
			}
		}, FocusEvent.getType());
I am unable to use ChangeDateHandler, since it automatically assumes "19" as "1900" and masks the text mid-way of text enter. Is there any other way i can handle this?

**Comment by crevete** [comment]
I'm sorry, but this is 100% a datepicker issue, but not a gwtbootstrap3-extras issue. Please create an issue in that project.
