### ISSUE TITLE
ToggleSwitch doesn't work

### ISSUE THREAD

**Issue by platform2** [gwtbootstrap3/gwtbootstrap3-extras#331]
I use GwtBootstrap Extra 0.9.3 in my application. I have some following code:

ToggleSwitch toggleSwitch = new ToggleSwitch();
FlowPanel  flowPanel = new FlowPanel();
flowPanel.add(toggleSwitch);

Once I run in Chrome, I got the following exception:

Exception caught: (TypeError) : $wnd.jQuery(...).bootstrapSwitch is not a function

I confirmed Window.jQuery is defined in Chrome development tool. My gwt.xml looks like the following:

<inherits name="org.gwtbootstrap3.client.Resources"/>
<inherits name="org.gwtbootstrap3.GwtBootstrap3"/>
<inherits name="org.gwtbootstrap3.extras.toggleswitch.ToggleSwitch"/>

Please help me out.

James

**Comment by crevete** [comment]
It seems that jQuery is inject several times. It should be injected ONLY ONCE.

<inherits name="org.gwtbootstrap3.client.Resources"/> ==> This will inject jQuery
<inherits name="org.gwtbootstrap3.GwtBootstrap3"/> ==> This will inject jQuery again
<inherits name="org.gwtbootstrap3.extras.toggleswitch.ToggleSwitch"/>
