### ISSUE TITLE
New SelectLanguage not work

### ISSUE THREAD

**Issue by liwston** [gwtbootstrap3/gwtbootstrap3-extras#332]
I was using version 0.9.1, when I updated it to 0.9.3...

when compile gwt I got this error 

`org.gwtbootstrap3.extras.select.client.ui.SelectLanguage cannot be resolved to a variable`

like this class not in 
`.org.gwtbootstrap3.extras.select.Select.gwt.xml`

**Comment by crevete** [comment]
This may be an issue of your local environment... As you can see, in the ```Select.gwt.xml```, we declare all contents of ```client``` package as GWT source code.
