### ISSUE TITLE
Summernote inside modal

### ISSUE THREAD

**Issue by liwston** [gwtbootstrap3/gwtbootstrap3-extras#333]
I have a Summernote inside a Modal, when I click on close in anyone Summernote modal window (like a "insert a link") my first Modal is closed too

![1](https://cloud.githubusercontent.com/assets/5443742/21766281/8353db12-d654-11e6-824c-f8c4a924edb0.JPG)
![2](https://cloud.githubusercontent.com/assets/5443742/21766283/8900b1d4-d654-11e6-8952-ea127fe123ef.JPG)

**Comment by crevete** [comment]
This is not a summernote issue, please check this: http://stackoverflow.com/questions/32162747/bootstrap-close-all-open-modals-prior-to-opening-a-new-one

**Comment by liwston** [comment]
Thank you, I solved this problem using mySummernote.setDialogsInBody(true);
