### ISSUE TITLE
Select value change event behavior

### ISSUE THREAD

**Issue by mrichterPP** [gwtbootstrap3/gwtbootstrap3-extras#335]
I recognized a strange behavior of the Bootstrap Select value change event. Switching between pages, one with a Select widget lead to a accumulation of events fired. 
It is reproducible in both demos (0.9.4 and snapshot):
- go to Extra->Select
- go somewhere else
- go back to Select
Now scroll to 'API and events' and select a new item in one of the Selects. You will see that the event log is logging two 'changed.bs.select event fired on simple select!'.  Repeating the page change is adding each time a further event. 

Is this a normal behavior?
Michael

**Comment by mrichterPP** [comment]
No comments on this? Feels like the question is too stupid for a answer...nobody else undergo this problem? Any tips?

**Comment by ahumellihuk** [comment]
I have the same issue - it seems to be failing to unbind javascript events in SelectBase::onUnload, as for every time it binds them in SelectBase::onLoad it adds a new handler

**Comment by sjardine** [comment]
Please fork the gwtbootstrap3-seed project and create an example that highlights this issue and I will check it out.

**Comment by ahumellihuk** [comment]
I think I found the issue - **SelectBase::onLoad** invokes **jQuery(e).selectpicker(options)**, which adds a new '**change**' handler every time that **triggers 'changed'** event. As a workaround, I extended the Select and MultipleSelect classes like this:

```
public class MySelect extends Select {

    @Override
    protected void onUnload() {
        super.onUnload();
        unbindChangeEvent(getElement());
    }

    private native void unbindChangeEvent(Element element) /*-{
        $wnd.$(element).off('change');
    }-*/;
}
```

Might submit a PR when I have time.

**Comment by schragmanuel** [comment]
Had the same problem. Thanks @ahumellihuk for the workaround! Works for me
