### ISSUE TITLE
org.gwtbootstrap3.extras.select.SelectNoResources / bootstrap-select-xxx.min.cache.js

### ISSUE THREAD

**Issue by manstis** [gwtbootstrap3/gwtbootstrap3-extras#336]
Hi,

We have a custom CSS in place of Bootstrap so opt to use the ```SelectNoResources``` module for the ```Select``` control. The problem is however this does not add the required JS to the page (as reported on https://github.com/gwtbootstrap3/gwtbootstrap3-extras/issues/308). The workaround being to inject the script manually. 

However it could also be accomplished by adding the entry-point ```org.gwtbootstrap3.extras.select.client.SelectEntryPoint``` to the ```SelectNoResources``` module definition and a ```public``` entry for ```<include path="resource/js">``` 

Is it unreasonable to expect "no resources" to at least include the minimal JS for the widget to work?

I guess I'm not reporting an issue as such; just want to understand if this behaviour is "by design".

With kind regards,

Mike

**Comment by sjardine** [comment]
"No Resources" means that no resources are injected.  You are responsible to inject the "resources" yourself.
