### ISSUE TITLE
Select-element: leaps over two or more list elements when using Down and Up-Keys

### ISSUE THREAD

**Issue by eugen-eugen** [gwtbootstrap3/gwtbootstrap3-extras#347]
Our setup:
The Web-Page includes THREE GWT-applications and each of them uses bootstrap3-extras-select.

Now, if I am in a select list and hit Down or Up keys, the cursor isn't moving to the next or previous line but rather make three moves forward resp. three moves back. 

Our analysis:
Each inclusion of bootstrap3-extras-select charges the html elements with key-events. We included bootstrap3-extras-select three times and therefore each hit of Down or Up keys leads to three moves of cursor.

**Comment by eugen-eugen** [comment]
pull request must be merged

**Comment by sjardine** [comment]
Please fork the seed project and create a test case that exhibits the problem. The gwtbootstrap3-demo project does not have this behavior.

I would recommend that you do not used the gwt modules with auto injection. Just inherit the modules that don't inject the scripts and inject them yourself in your index.html file or whatever.

**Comment by sjardine** [comment]
I don't think this is a bug.  I am pretty sure this is due to incorrect use of the modules that auto injects scripts.  Will reopen if a verifiable test case is given.
