### ISSUE TITLE
getView() undefined

### ISSUE THREAD

**Issue by saadhamouine** [gwtbootstrap3/gwtbootstrap3-extras#350]
Hi, I'm trying to use the getView method so i would know the start and end date of my view but it always returns undefined.

**Comment by sjardine** [comment]
This is not nearly enough information to even comment.  Please provide a verifiable test case.

**Comment by saadhamouine** [comment]
Ok here's a simple test case. I want to only load events from the DB that exist in the timeframe of the View(Month, Week, Day)
//
FullCalendar calendar = new FullCalendar("id",Viewoption.month,....);
Date start = calendar.getView().getStart();
Date end = calendar.getView().getEnd();
DB.loadevents(start,end);
//
the problem is the method getView returns always null.

**Comment by sjardine** [comment]
I'm sorry. This is not really a test case. Please fork the gwtbootstrap-seed project, modify the project to identify the problem and then send me the link to your project.
