### ISSUE TITLE
Add typeahead.js support

### ISSUE THREAD

**Issue by tomekziel** [gwtbootstrap3/gwtbootstrap3-extras#5]
Typeahead component was dropped from gwtbootstrap3. It would be great to have GWT wrapper for typeahead.js (http://twitter.github.io/typeahead.js/)

**Comment by jgodi** [comment]
https://github.com/gwtbootstrap3/gwtbootstrap3/pull/306, when this is merged in I will be closing this.

**Comment by jgodi** [comment]
Closing this, as we have the Suggest Box wrapped.

**Comment by payammeyer** [comment]
Excellent, thank you guys so much for the great work.
