### ISSUE TITLE
Select's "Option" should have setter/getter for object

### ISSUE THREAD

**Issue by davidbuhler** [gwtbootstrap3/gwtbootstrap3-extras#51]
Select Option should have a setter/getter for a generic object. In doing so, the developer can store a serialized object (a DTO/Database proxy entity) in the selected option.

Another approach would allow the developer to pass in a generic "Object" instead of the "Option". Then, the developer could specify the label property of the Object to display on the Select control (label="ingredients" or label="name"). 

That's how Flex allows the Select to accept generic objects, while still returning a serialized DTO upon request.

http://flex.apache.org/asdoc/spark/components/ComboBox.html

**Comment by crevete** [comment]
I'm not sure what you want to do, but if you just want to store an object (or someting similar) into the Option, you can just create an extended option with your getter/setter.

**Comment by crevete** [comment]
@davidbuhler without your reply, I close this issue. Please leave a comment if you want to talk again.

**Comment by davidbuhler** [comment]
I'd have to look at the code base to see what changes I made to my wrapper to create a typed select with most of my complaints fixed in my fork. I think I left the typed select hoping someone would fork my changes and finish them up. I got some good feedback about the changes I needed to make before making the pull request, but never got around to making the changes.

**Comment by crevete** [comment]
Anyway please take a look at the new implementation of the select. By default, we provide a simple ```Select```(String) and a ```MultipleSelect```(List<String>) implementations. You may also extend the generic ```SelectBase``` for any typed value.

**Comment by davidbuhler** [comment]
I will be able to get around to looking this week. I'm actually in the process of updating and porting the GWT app, which I need to complete by next Friday.

**Comment by crevete** [comment]
@davidbuhler any news ?

**Comment by davidbuhler** [comment]
I'm afraid not. I was hoping to move back to this project, but work obligations always bubble up when I think I have downtime approaching. I apologize.

**Comment by crevete** [comment]
@davidbuhler So I close this issue for now. Please fell free to reopen it if necessary.
