### ISSUE TITLE
Add a name in the Select widget so we can submit it...

### ISSUE THREAD

**Issue by stratosgear** [gwtbootstrap3/gwtbootstrap3-extras#52]
Or, if the functionality is already there, how do I specify a name in the html select tag.

I just can't seem to be able to correctly submit a Select widget. Looking through the generated html code the select lacks a valid name:

    <select class="bootstrap-select" style="display: none;">
    ...
    ...
    </select>

**Comment by klimeryk** [comment]
I want the 0.9 ASAP, so I'm pulling my weight :)
