### ISSUE TITLE
Growl Options should require typed AlertType for Alert Style

### ISSUE THREAD

**Issue by davidbuhler** [gwtbootstrap3/gwtbootstrap3-extras#71]
To set the Alert Type style, the GrowlOptions currently require the developer to use one of the following:

setDangerType()
setInfoType()
setSuccessType()
setWarningType()

~~~java
    public final native void setInfoType() /*-{
        this.type = 'info';
    }-*/;

    public final native void setSuccessType() /*-{
        this.type = 'success';
    }-*/;

    public final native void setDangerType() /*-{
        this.type = 'danger';
    }-*/;

    public final native void setWarningType() /*-{
        this.type = 'warning';
    }-*/;

~~~
For consistency with the rest of the framework, to pass a parameter in the setter, and to use a typed Enum, these should be consolidated into:
~~~java
setType(AlertType alertType)

**Comment by jgodi** [comment]
Closed via: https://github.com/gwtbootstrap3/gwtbootstrap3-extras/pull/110
