### ISSUE TITLE
Datetimepicker sets time to midnight

### ISSUE THREAD

**Issue by dillerch** [gwtbootstrap3/gwtbootstrap3-extras#74]
When selecting 12:00, the getValue() method returns the correct year, month and day but 00:00. Everything else works as it should, 13:00 => 13:00 and so on.

My parameters are forceParse="false" autoClose="true" startView="MONTH" minView="DAY" maxView="MONTH" language="DE" format="dd.mm.yyyy HH:ii" minuteStep="60"

**Comment by crevete** [comment]
This is also fixed after upgrading dateTimePicker to 2.3.5
