### ISSUE TITLE
DateTimePicker loses set format

### ISSUE THREAD

**Issue by dw9** [gwtbootstrap3/gwtbootstrap3-extras#80]
E.g. if you setFormat("dd.mm.yyyy"), then 'format' will be set to "dd.mm.yyyy" and then after that, the format will be converted to "dd.MM.yyyy" in setDateTimeFormat() but the 'format' member will not be updated. Since 'format' is not updated, this will cause the date format to change back to "dd.mm.yyy" after you have select a value.

**Comment by jgodi** [comment]
To correctly change the format after the DateTimeBox has been loaded you must call:

```
dateTimeBox.setFormat("dd.mm.yyyy");
dateTimeBox.reload();
```

I will update the demo to reflect this. Thanks!
