### ISSUE TITLE
DateTimePicker format changes times after 13:00 to 12h format without AM/PM information

### ISSUE THREAD

**Issue by atfornes** [gwtbootstrap3/gwtbootstrap3-extras#83]
Same problem as #36 

When using DateTimePicker, either setting programatically or chosing with the picker a time equal or bigger than 13:00 results in unexpected behavior: the time is set to the 12 hours format but not "PM" is added to the textbox string.

The problem can be reproduced by simply adding a DateTimePicker as in this simple example: https://github.com/atfornes/sampleGwtBootstrap3DateTimePicker/blob/master/src/foo/client/SampleDateTimePicker.java

Checked with version 0.8.1 with maven as in https://github.com/atfornes/sampleGwtBootstrap3DateTimePicker

**Comment by crevete** [comment]
This is the same as #240 I think. It is fixed.
