### ISSUE TITLE
Update Growl to version 2.0.1

### ISSUE THREAD

**Issue by zlamalp** [gwtbootstrap3/gwtbootstrap3-extras#85]
Hi, I'd like to update Growl plugin from 1.0.6 to 2.0.1 because I need custom offset per axis. Do you have any plans for this or you want to stick with older version ? I'll do it anyway for my own purpose, but I'd like to share the result, since it can be useful to others too.

There are some notable changes in Growl itslef, like using only CSS animations, clickable notification, actions onShow, onShown, onHide and onHidden, method to close all displayed Growls etc.

**Comment by jgodi** [comment]
Any update on this?

**Comment by zlamalp** [comment]
Hi, I have almost complete version in my growUpdate branch, but there is a bug in original JS library, which doesn't fire any event. So I'm still waiting for mouse0270/bootstrap-growl#28 to complete my task. I can prepare version without events if you wish.

**Comment by jgodi** [comment]
I would say no events for now. But create a second issue for when bootstrap-growl fixes their issue with events. That way we can get this out the door :)

Thanks!

**Comment by crevete** [comment]
I'm waiting for this update 2.0.1 for long time :-) Please make a PR as soon as possible even if there is still an event bug. Thanks a lot

**Comment by zlamalp** [comment]
Hi, I just made PR #110 with Growl without events. I'm just unsure about inheriting GwtBootstrap3 module, but I need ``Styles`` and ``IconType`` classes, which are in base module. I will make separate PR for the demo app.

**Comment by crevete** [comment]
I guess you may inherit the CDN module (or base module ?), since the GwtBootstrap3 module includes all resources stuff (themes, etc.)

```
<inherits name="org.gwtbootstrap3.GwtBootstrap3CDN"/>
```

**Comment by jgodi** [comment]
For the inherits issue, these are extras for the main library. Users are supposed to already inherit the GwtBootstrap3 module before inheriting your module. Same goes with the DateTimePicker and others. None of them inherit GwtBootstrap3 because the user can't use the extras without inheriting it themselves.

**Comment by crevete** [comment]
@zlamalp Can you make the changes ASAP ?

**Comment by jgodi** [comment]
```<inherits name="org.gwtbootstrap3.GwtBootstrap3Base"/>```

Will work too.

**Comment by jgodi** [comment]
Added it for you, thanks for the help! We appreciate it. Demo looks great!
