### ISSUE TITLE
Update Bootstrap Slider to latest version

### ISSUE THREAD

**Issue by stratosgear** [gwtbootstrap3/gwtbootstrap3-extras#93]
By browsing through the code I see that the Slider does not accept an array, so I doesn't look I can select a range of values.

Am I reading it wrong?

**Comment by crevete** [comment]
@jgodi  FYI, I'm working on it now (version 4.5). Hope that will be done for incoming days.

**Comment by eliovir** [comment]
@crevete I do not manage to hide a slider. Can you see if the attribute `visible="false"` or the method `.setVisible(false)` work with the new version? If not, I'll open another issue.

**Comment by crevete** [comment]
The ```setVisible``` method is based on the ```<input>``` element ; but it does not take effect on the initialized slider element (```<div>```): 

A generated slider is something like this :
```
<div class="slider slider-horizontal" id="ex1Slider">
  <div class="slider-track">...</div>
  <div class="tooltip tooltip-main top" style="left: 76%; margin-left: -55px;">...</div>
  <div class="tooltip tooltip-min top" style="">...</div>
  <div class="tooltip tooltip-max bottom" style="top: 18px;">...</div>
</div>
<input type="text" data-slider-value="14" data-slider-step="1" data-slider-max="20" data-slider-min="-5" data-slider-id="ex1Slider" id="ex1" style="display: none;" data="value: '14'" value="14">
```

So in the new version, it would better to override the ```setVisible``` and ```isVisible``` methods to make it work. Thanks for your input !

**Comment by eliovir** [comment]
@crevete, thanks for your explanation. Do you want I write a new issue?

Which ''bootstrap-slider'' will you use? [Yours](https://github.com/crevete/bootstrap-slider), [seiyria's](https://github.com/seiyria/bootstrap-slider), [eyecon's](http://www.eyecon.ro/bootstrap-slider/) ?

Will it support range selector?

**Comment by crevete** [comment]
@eliovir No, you don't have to write a new one, it will be fixed in the new version.
The slider I use is seiyria's, not mine :-) The current version is based on the eyecon's one I guess.
Yes, it supports range slider. Actually the new version contains 2 sliders : one with numeric value, one with range support.

**Comment by eliovir** [comment]
Really nice. I'm waiting for the next version!
