### ISSUE TITLE
Select component doesn't get enabled once it is disabled

### ISSUE THREAD

**Issue by RajGaurav** [gwtbootstrap3/gwtbootstrap3-extras#94]
http://gwtbootstrap3.github.io/gwtbootstrap3-demo/#select

Select element when disabled like below

Select select = new Select;
select.setEnabled(false);

And then try to enable the same like below

select.setEnabled(true);

Yet it doesn't get enabled.

**Comment by jgodi** [comment]
For the these custom wrapped selects you have to call ```refresh()``` after any changes.

So in your case:

```
select.setEnabled(true);
select.refresh();
```

I will update the demo to show this.
