### ISSUE TITLE
Bootstrap Select Demo page not working on IE 8

### ISSUE THREAD

**Issue by IvanLazov** [gwtbootstrap3/gwtbootstrap3-extras#96]
Opening the demo page for the Select widget (http://gwtbootstrap3.github.io/gwtbootstrap3-demo/#select) doesn't work on IE 8. It ends up with an unknow runtime error. 

Here is a screenshot
![image](https://cloud.githubusercontent.com/assets/1061394/4935763/deeebad0-65b0-11e4-940d-93f58219937a.png)

**Comment by ArloL** [comment]
I can reproduce an error in IE 8. Looking into it right now.

**Comment by ArloL** [comment]
It's because of the <ul> in the setInnerHTML. Check the documentation of GWT's HTMLPanel where they talk about it. Maybe I'll prepare a fix tomorrow.

**Comment by jgodi** [comment]
Where is this setInnerHTML at?

**Comment by ArloL** [comment]
https://github.com/gwtbootstrap3/gwtbootstrap3/blob/bbd8c26b691f275103b965c768e2b6598bd338e9/gwtbootstrap3/src/main/java/org/gwtbootstrap3/client/ui/base/mixin/HTMLMixin.java#L39

**Comment by jgodi** [comment]
@ArloL Did you fixes fix this issue? I do not have access to IE8 so I cannot test it.

**Comment by ArloL** [comment]
Yes, any one of the three fixes would have done it. All three even better.

On a sidenote: I use a modern.ie VM in VirtualBox for testing IE 8 which works great (including classic dev mode).

**Comment by jgodi** [comment]
Thanks!

**Comment by jgodi** [comment]
Ha, didn't mean to open/close again. Cat jumped on keyboard :P

**Comment by ArloL** [comment]
Too good to be true :smile:
