### ISSUE TITLE
Time only datepicker reverts year to 1899

### ISSUE THREAD

**Issue by jossag** [gwtbootstrap3/gwtbootstrap3-extras#98]
Using the datetimepicker in "Time only" mode and setting a date, the date in the header changes the year to 1899.

Can be reproduced in the demo (http://gwtbootstrap3.github.io/gwtbootstrap3-demo/#dateTimePicker)

Select a time in the time only datepicker.
Click it again, the date header should read 1899.

**Comment by jgodi** [comment]
This is a bug in the underlying library. https://github.com/smalot/bootstrap-datetimepicker/issues/33.

When that gets fixed, we will fix it on our end. Thanks!

**Comment by pvdptje** [comment]
If you don't mind not displaying any text at all when picking a time, you can always hide it with css.

```
<style>
.table-condensed .switch {
    visibility: hidden;
}
</style>
```

**Comment by crevete** [comment]
The demo page is updated to show how to fix this issue.
